version: '3.8'
services:
  app:
    build: 
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - VITE_USER_NODE_ENV=development
    deploy:
      resources:
        limits:
          memory: 2GB
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=contafricax
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c shared_buffers=256MB -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1GB
    restart: unless-stopped
    
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
