version: '3.8'
services:
  app:
    image: ghcr.io/${GITHUB_USERNAME}/contafricax-app:latest
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    restart: always

  db:
    image: postgres:latest
    volumes:
      - db_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=contafricax
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  db_prod:
