name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  POSTGRES_USER: ${{ secrets.DB_USER }}
  POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and test
      env:
        NODE_ENV: test
      run: |
        docker-compose build
        docker-compose up -d
        docker-compose exec -T app npm run lint
    
    - name: Check application health
      run: |
        curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:5173

    - name: Build production image
      run: docker build --target production .
